#!/bin/bash

pandoc markdown_versions/hawaiian_salad.md -o hawaiian_salad.html
pandoc markdown_versions/taiwanese_pork.md -o taiwanese_pork.html
pandoc markdown_versions/polynesian_pork.md -o polynesian_pork.html
